//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.23 at 01:53:12 PM MSK 
//


package com.restfit.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="distance" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="run_time" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="race_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "distance",
    "runTime",
    "raceDate"
})
@XmlRootElement(name = "addUserFitDataRequest")
public class AddUserFitDataRequest {

    protected double distance;
    @XmlElement(name = "run_time")
    protected int runTime;
    @XmlElement(name = "race_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar raceDate;

    /**
     * Gets the value of the distance property.
     * 
     */
    public double getDistance() {
        return distance;
    }

    /**
     * Sets the value of the distance property.
     * 
     */
    public void setDistance(double value) {
        this.distance = value;
    }

    /**
     * Gets the value of the runTime property.
     * 
     */
    public int getRunTime() {
        return runTime;
    }

    /**
     * Sets the value of the runTime property.
     * 
     */
    public void setRunTime(int value) {
        this.runTime = value;
    }

    /**
     * Gets the value of the raceDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRaceDate() {
        return raceDate;
    }

    /**
     * Sets the value of the raceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRaceDate(XMLGregorianCalendar value) {
        this.raceDate = value;
    }

}
