//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.23 at 01:53:12 PM MSK 
//


package com.restfit.soap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userFitDatas" type="{http://localhost:8080/soap}userFitDatas" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userFitDatas"
})
@XmlRootElement(name = "getUserFitDataByLoginResponse")
public class GetUserFitDataByLoginResponse {

    @XmlElement(required = true)
    protected List<UserFitDatas> userFitDatas;

    /**
     * Gets the value of the userFitDatas property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userFitDatas property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserFitDatas().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserFitDatas }
     * 
     * 
     */
    public List<UserFitDatas> getUserFitDatas() {
        if (userFitDatas == null) {
            userFitDatas = new ArrayList<UserFitDatas>();
        }
        return this.userFitDatas;
    }

    public void setUserFitDatas(List<UserFitDatas> value) {
        this.userFitDatas = value;
    }

}
