//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.23 at 01:53:12 PM MSK 
//


package com.restfit.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the localhost._8080.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: localhost._8080.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetUserFitDataByLoginRequest }
     * 
     */
    public GetUserFitDataByLoginRequest createGetUserFitDataByLoginRequest() {
        return new GetUserFitDataByLoginRequest();
    }

    /**
     * Create an instance of {@link GetUserFitDataByLoginResponse }
     * 
     */
    public GetUserFitDataByLoginResponse createGetUserFitDataByLoginResponse() {
        return new GetUserFitDataByLoginResponse();
    }

    /**
     * Create an instance of {@link UserFitDatas }
     * 
     */
    public UserFitDatas createUserFitDatas() {
        return new UserFitDatas();
    }

    /**
     * Create an instance of {@link GetUserFitDatasRequest }
     * 
     */
    public GetUserFitDatasRequest createGetUserFitDatasRequest() {
        return new GetUserFitDatasRequest();
    }

    /**
     * Create an instance of {@link GetUserFitDatasResponse }
     * 
     */
    public GetUserFitDatasResponse createGetUserFitDatasResponse() {
        return new GetUserFitDatasResponse();
    }

    /**
     * Create an instance of {@link AddUserFitDataResponse }
     * 
     */
    public AddUserFitDataResponse createAddUserFitDataResponse() {
        return new AddUserFitDataResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link AddUserFitDataRequest }
     * 
     */
    public AddUserFitDataRequest createAddUserFitDataRequest() {
        return new AddUserFitDataRequest();
    }

}
